// playground/svelte/InnerComp.svelte
<script>
  import { getContext } from 'svelte';

  const swiper = getContext('swiper');
  const slideData = getContext('swiperSlide');
  console.log(slideData);
</script>

<div style="line-height: 1; margin-top: 20px;">
  <slot /> - {slideData.isActive} - {slideData.isNext}
  <button
    on:click={() => {
      swiper.slideNext();
    }}>Next</button
  >
</div>

// playground/vue/innerComp.vue
<template>
  test - {{ swiperSlide.isActive }} - {{ swiperSlide.isNext }}
  <button @click="swiper.slideNext()">Next</button>
</template>
<script>
import { inject } from 'vue';
export default {
  setup() {
    const swiper = inject('swiper');
    const swiperSlide = inject('swiperSlide');
    console.log({ swiper, swiperSlide });
    return {
      swiper,
      swiperSlide,
    };
    // console.log(swiper, slideData);
  },
};
</script>
