// src/react/swiper.tsx
import React, {
  forwardRef,
  useEffect,
  useRef,
  useState,
  type ElementType,
  type ForwardedRef,
  type HTMLAttributes,
  type MutableRefObject,
  type ReactNode,
} from 'react';
import SwiperCore from '../swiper';
import { getParams } from '../components-shared/get-params';
import { mountSwiper } from '../components-shared/mount-swiper';
import {
  needsScrollbar,
  needsNavigation,
  needsPagination,
  uniqueClasses,
  extend,
  wrapperClass,
} from '../components-shared/utils';
import { getChangedParams } from '../components-shared/get-changed-params';
import { getChildren } from './get-children';
import { updateSwiper } from '../components-shared/update-swiper';
import { renderVirtual, type VirtualData } from './virtual';
import { updateOnVirtualData } from '../components-shared/update-on-virtual-data';
import { useIsomorphicLayoutEffect } from './use-isomorphic-layout-effect';
import { SwiperContext } from './context';
import type {
  Swiper as SwiperClass,
  SwiperOptions,
  SwiperEventHandler,
} from '../core/core';

type DropEvents =
  | 'onProgress'
  | 'onClick'
  | 'onTouchEnd'
  | 'onTouchMove'
  | 'onTouchStart'
  | 'onTransitionEnd'
  | 'onKeyPress'
  | 'onDoubleClick'
  | 'onScroll'
  | 'onResize';

export interface SwiperProps
  extends Omit<HTMLAttributes<HTMLElement>, DropEvents>,
    SwiperOptions {
  tag?: string;
  wrapperTag?: string;
  onSwiper?: (swiper: SwiperClass) => void;
  children?: ReactNode;
}

const Swiper = forwardRef<HTMLElement, SwiperProps>(function Swiper(propsArg, externalElRef) {
  const {
    className,
    tag: Tag = 'div',
    wrapperTag: WrapperTag = 'div',
    children,
    onSwiper,
    ...rest
  } = propsArg ?? {};

  let eventsAssigned = false;
  const [containerClasses, setContainerClasses] = useState('swiper');
  const [virtualData, setVirtualData] = useState<VirtualData | null>(null);
  const [breakpointChanged, setBreakpointChanged] = useState(false);
  const initializedRef = useRef(false);
  const swiperElRef = useRef<HTMLElement | null>(null);
  const swiperRef = useRef<SwiperClass | null>(null);
  const oldPassedParamsRef = useRef<Record<string, unknown> | null>(null);
  const oldSlides = useRef<ReturnType<typeof getChildren>['slides'] | null>(null);

  const nextElRef = useRef<HTMLDivElement | null>(null);
  const prevElRef = useRef<HTMLDivElement | null>(null);
  const paginationElRef = useRef<HTMLDivElement | null>(null);
  const scrollbarElRef = useRef<HTMLDivElement | null>(null);

  const {
    params: swiperParams,
    passedParams,
    rest: restProps,
    events,
  } = getParams(rest as Record<string, unknown>);

  const { slides, slots } = getChildren(children);

  const onBeforeBreakpoint = (): void => {
    setBreakpointChanged(!breakpointChanged);
  };

  Object.assign(swiperParams.on as Record<string, SwiperEventHandler>, {
    _containerClasses(_swiper: SwiperClass, classes: string) {
      setContainerClasses(classes);
    },
  });

  const initSwiper = (): void => {
    Object.assign(swiperParams.on as Record<string, SwiperEventHandler>, events);
    eventsAssigned = true;
    const passParams = { ...swiperParams } as SwiperOptions & { wrapperClass?: string };
    delete passParams.wrapperClass;
    swiperRef.current = new SwiperCore(passParams);
    const instance = swiperRef.current;
    if (instance.virtual && instance.params.virtual?.enabled) {
      instance.virtual.slides = slides;
      const extendWith = {
        cache: false,
        slides,
        renderExternal: setVirtualData,
        renderExternalUpdate: false,
      };
      extend(instance.params.virtual, extendWith);
      if (instance.originalParams.virtual) extend(instance.originalParams.virtual, extendWith);
    }
  };

  if (!swiperElRef.current) {
    initSwiper();
  }

  if (swiperRef.current) {
    swiperRef.current.on('_beforeBreakpoint', onBeforeBreakpoint);
  }

  const attachEvents = (): void => {
    if (eventsAssigned || !events || !swiperRef.current) return;
    Object.keys(events).forEach((eventName) => {
      swiperRef.current!.on(eventName, events[eventName]!);
    });
  };

  const detachEvents = (): void => {
    if (!events || !swiperRef.current) return;
    Object.keys(events).forEach((eventName) => {
      swiperRef.current!.off(eventName, events[eventName]!);
    });
  };

  useEffect(() => {
    return () => {
      if (swiperRef.current) swiperRef.current.off('_beforeBreakpoint', onBeforeBreakpoint);
    };
  });

  useEffect(() => {
    if (!initializedRef.current && swiperRef.current) {
      swiperRef.current.emitSlidesClasses();
      initializedRef.current = true;
    }
  });

  useIsomorphicLayoutEffect(() => {
    if (externalElRef) {
      if (typeof externalElRef === 'function') {
        externalElRef(swiperElRef.current);
      } else {
        (externalElRef as MutableRefObject<HTMLElement | null>).current = swiperElRef.current;
      }
    }
    if (!swiperElRef.current) return;
    if (swiperRef.current && swiperRef.current.destroyed) {
      initSwiper();
    }

    mountSwiper(
      {
        el: swiperElRef.current,
        nextEl: nextElRef.current,
        prevEl: prevElRef.current,
        paginationEl: paginationElRef.current,
        scrollbarEl: scrollbarElRef.current,
        swiper: swiperRef.current!,
      },
      swiperParams,
    );

    if (onSwiper && swiperRef.current && !swiperRef.current.destroyed) onSwiper(swiperRef.current);
    return () => {
      if (swiperRef.current && !swiperRef.current.destroyed) {
        swiperRef.current.destroy(true, false);
      }
    };
  }, []);

  useIsomorphicLayoutEffect(() => {
    attachEvents();
    const changedParams = getChangedParams(
      passedParams,
      oldPassedParamsRef.current,
      slides,
      oldSlides.current,
      (c) => c.key,
    );
    oldPassedParamsRef.current = passedParams;
    oldSlides.current = slides;
    if (changedParams.length && swiperRef.current && !swiperRef.current.destroyed) {
      updateSwiper({
        swiper: swiperRef.current,
        slides,
        passedParams,
        changedParams,
        nextEl: nextElRef.current,
        prevEl: prevElRef.current,
        scrollbarEl: scrollbarElRef.current,
        paginationEl: paginationElRef.current,
      });
    }
    return () => {
      detachEvents();
    };
  });

  useIsomorphicLayoutEffect(() => {
    updateOnVirtualData(swiperRef.current);
  }, [virtualData]);

  function renderSlides(): ReactNode {
    if (swiperParams.virtual) {
      return renderVirtual(swiperRef.current, slides, virtualData);
    }
    return slides.map((child, index) =>
      React.cloneElement(child, { swiper: swiperRef.current, swiperSlideIndex: index }),
    );
  }

  const TagComponent = Tag as ElementType;
  const WrapperComponent = WrapperTag as ElementType;

  return (
    <TagComponent
      ref={swiperElRef as ForwardedRef<HTMLElement>}
      className={uniqueClasses(`${containerClasses}${className ? ` ${className}` : ''}`)}
      {...(restProps as HTMLAttributes<HTMLElement>)}
    >
      <SwiperContext.Provider value={swiperRef.current}>
        {slots['container-start']}
        <WrapperComponent className={wrapperClass(swiperParams.wrapperClass)}>
          {slots['wrapper-start']}
          {renderSlides()}
          {slots['wrapper-end']}
        </WrapperComponent>
        {needsNavigation(swiperParams) && (
          <>
            <div ref={prevElRef} className="swiper-button-prev" />
            <div ref={nextElRef} className="swiper-button-next" />
          </>
        )}
        {needsScrollbar(swiperParams) && (
          <div ref={scrollbarElRef} className="swiper-scrollbar" />
        )}
        {needsPagination(swiperParams) && (
          <div ref={paginationElRef} className="swiper-pagination" />
        )}
        {slots['container-end']}
      </SwiperContext.Provider>
    </TagComponent>
  );
});

Swiper.displayName = 'Swiper';

export { Swiper };

// src/solid/swiper.js
import SwiperCore from 'swiper';
import { createEffect, createSignal, onCleanup, Show, splitProps } from 'solid-js';
import { getParams } from './get-params.js';
import { mountSwiper } from './mount-swiper.js';
import {
  needsScrollbar,
  needsNavigation,
  needsPagination,
  uniqueClasses,
  extend,
} from './utils.js';
import { renderLoop, calcLoopedSlides } from './loop.js';
import { getChangedParams } from './get-changed-params.js';
import { getChildren } from './get-children.js';
import { updateSwiper } from './update-swiper.js';
import { renderVirtual, updateOnVirtualData } from './virtual.js';
import { SwiperContext } from './context.js';

const Swiper = (props) => {
  let eventsAssigned = false;
  const [containerClasses, setContainerClasses] = createSignal('swiper');
  const [virtualData, setVirtualData] = createSignal(null);
  const [breakpointChanged, setBreakpointChanged] = createSignal(false);

  // The variables bellow are mofied by SolidJS and can't be const
  let initializedRef = false; // eslint-disable-line prefer-const
  let swiperElRef = null; // eslint-disable-line prefer-const
  let swiperRef = null; // eslint-disable-line prefer-const
  let oldPassedParamsRef = null; // eslint-disable-line prefer-const
  let oldSlides = null; // eslint-disable-line prefer-const

  let nextElRef = null; // eslint-disable-line prefer-const
  let prevElRef = null; // eslint-disable-line prefer-const
  let paginationElRef = null; // eslint-disable-line prefer-const
  let scrollbarElRef = null; // eslint-disable-line prefer-const

  const [local, rest] = splitProps(props, [
    'children',
    'class',
    'onSwiper',
    'ref',
    'Tag',
    'WrapperTag',
  ]);

  const { params: swiperParams, passedParams, rest: restProps, events } = getParams(rest);

  const { slides, slots } = getChildren(local.children);

  const onBeforeBreakpoint = () => {
    setBreakpointChanged(!breakpointChanged);
  };

  Object.assign(swiperParams.on, {
    _containerClasses(swiper, classes) {
      setContainerClasses(classes);
    },
  });

  const initSwiper = () => {
    // init swiper
    Object.assign(swiperParams.on, events);
    eventsAssigned = true;
    swiperRef.current = new SwiperCore(swiperParams);
    swiperRef.current.loopCreate = () => {};
    swiperRef.current.loopDestroy = () => {};
    if (swiperParams.loop) {
      swiperRef.current.loopedSlides = calcLoopedSlides(slides, swiperParams);
    }
    if (swiperRef.current.virtual && swiperRef.current.params.virtual.enabled) {
      swiperRef.current.virtual.slides = slides;
      const extendWith = {
        cache: false,
        slides,
        renderExternal: setVirtualData,
        renderExternalUpdate: false,
      };
      extend(swiperRef.current.params.virtual, extendWith);
      extend(swiperRef.current.originalParams.virtual, extendWith);
    }
  };

  if (!swiperElRef.current) {
    initSwiper();
  }

  // Listen for breakpoints change
  if (swiperRef.current) {
    swiperRef.current.on('_beforeBreakpoint', onBeforeBreakpoint);
  }

  const attachEvents = () => {
    if (eventsAssigned || !events || !swiperRef.current) return;
    Object.keys(events).forEach((eventName) => {
      swiperRef.current.on(eventName, events[eventName]);
    });
  };

  const detachEvents = () => {
    if (!events || !swiperRef.current) return;
    Object.keys(events).forEach((eventName) => {
      swiperRef.current.off(eventName, events[eventName]);
    });
  };

  createEffect(() => {
    return () => {
      if (swiperRef.current) swiperRef.current.off('_beforeBreakpoint', onBeforeBreakpoint);
    };
  });

  // set initialized flag
  createEffect(() => {
    if (!initializedRef.current && swiperRef.current) {
      swiperRef.current.emitSlidesClasses();
      initializedRef.current = true;
    }
  });

  // mount swiper
  createEffect(() => {
    if (local.ref) {
      local.ref = swiperElRef.current;
    }
    if (!swiperElRef.current) return;
    if (swiperRef.current.destroyed) {
      initSwiper();
    }

    mountSwiper(
      {
        el: swiperElRef,
        nextEl: nextElRef,
        prevEl: prevElRef,
        paginationEl: paginationElRef,
        scrollbarEl: scrollbarElRef,
        swiper: swiperRef,
      },
      swiperParams,
    );

    if (local.onSwiper) local.onSwiper(swiperRef);
    // eslint-disable-next-line
    return () => {
      if (swiperRef.current && !swiperRef.current.destroyed) {
        swiperRef.current.destroy(true, false);
      }
    };
  });

  // watch for params change
  createEffect(() => {
    attachEvents();
    const changedParams = getChangedParams(
      passedParams,
      oldPassedParamsRef.current,
      slides,
      oldSlides.current,
    );
    oldPassedParamsRef.current = passedParams;
    oldSlides.current = slides;
    if (changedParams.length && swiperRef.current && !swiperRef.current.destroyed) {
      updateSwiper({
        swiper: swiperRef.current,
        slides,
        passedParams,
        changedParams,
        nextEl: nextElRef.current,
        prevEl: prevElRef.current,
        scrollbarEl: scrollbarElRef.current,
        paginationEl: paginationElRef.current,
      });
    }
    onCleanup(detachEvents);
  });

  // update on virtual update
  createEffect(() => {
    updateOnVirtualData(swiperRef.current);
  });

  // bypass swiper instance to slides
  function renderSlides() {
    if (swiperParams.virtual) {
      return renderVirtual(swiperRef.current, slides, virtualData);
    }
    if (!swiperParams.loop || (swiperRef.current && swiperRef.current.destroyed)) {
      return slides.map((child) => {
        const node = child.cloneElement();
        node.swiper = swiperRef;
        return node;
      });
    }
    return renderLoop(swiperRef.current, slides, swiperParams);
  }

  /* eslint-disable react/react-in-jsx-scope */
  /* eslint-disable react/no-unknown-property */

  return (
    <local.Tag
      ref={swiperElRef}
      class={uniqueClasses(`${containerClasses}${local.class ? ` ${local.class}` : ''}`)}
      {...restProps}
    >
      <SwiperContext.Provider value={swiperRef}>
        {slots['container-start']}

        <local.WrapperTag class="swiper-wrapper">
          {slots['wrapper-start']}
          {renderSlides()}
          {slots['wrapper-end']}
        </local.WrapperTag>

        <Show when={needsNavigation(swiperParams)}>
          <div ref={prevElRef} class="swiper-button-prev" />
          <div ref={nextElRef} class="swiper-button-next" />
        </Show>
        <Show when={needsScrollbar(swiperParams)}>
          <div ref={scrollbarElRef} class="swiper-scrollbar" />
        </Show>
        <Show when={needsPagination(swiperParams)}>
          <div ref={paginationElRef} class="swiper-pagination" />
        </Show>

        {slots['container-end']}
      </SwiperContext.Provider>
    </local.Tag>
  );
};

Swiper.displayName = 'Swiper';

export { Swiper };
